services:
  groq:
    api_key: ${GROQ_API_KEY}
    models:
      - llama3-groq-70b-8192-tool-use-preview
      - llama3-groq-8b-8192-tool-use-preview
      - llama-3.1-70b-versatile
      - llama-3.1-8b-instant
    default_model: llama-3.1-70b-versatile

  ollama:
    host: localhost
    port: 11434
    models:
      - llama2
      - mistral
      - codellama
    default_model: llama2

  cerebras:
    api_key: ${CEREBRAS_API_KEY}
    models:
      - cerebras-gpt-13b
      - cerebras-gpt-6.7b
    default_model: cerebras-gpt-13b

logging:
  level: INFO
  file: llmserver.log

api:
  host: 0.0.0.0
  port: 5000

console:
  enabled: true